# Generated by Django 4.2.1 on 2023-05-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_password_user_passw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passw',
            new_name='password',
        ),
    ]
